name: Build MacroWalPad

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli
    steps:
      - name: Scarica repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Prepara file e Compila
        run: |
          git config --global --add safe.directory '*'
          qmk config user.qmk_home=$(pwd)

          # 1. Rinomina la cartella in tutto minuscolo se ha maiuscole
          if [ -d "keyboards/handwired/MacroWalPad" ]; then
            mv keyboards/handwired/MacroWalPad keyboards/handwired/macrowalpad
          fi

          # 2. Rimuove VIAL_ENABLE dal rules.mk principale (evita l'errore del validatore)
          sed -i '/VIAL_ENABLE/d' keyboards/handwired/macrowalpad/rules.mk

          # 3. Assicura che VIAL sia abilitato nel keymap dedicato
          mkdir -p keyboards/handwired/macrowalpad/keymaps/vial
          printf "VIA_ENABLE = yes\nVIAL_ENABLE = yes\n" > keyboards/handwired/macrowalpad/keymaps/vial/rules.mk

          # 4. Compila il firmware
          make handwired/macrowalpad:vial

      - name: Salva UF2
        uses: actions/upload-artifact@v4
        with:
          name: macrowalpad_firmware
          path: |
            *.uf2
            .build/*.uf2
            **/*.uf2
